version: '2'
services:
  jenkins:
    build:
      context: ./jenkins
    volumes:
      - /mnt_docker/jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
    networks:
      - front
  nginx:
    build:
      context: ./nginx
      args:
        BASIC_USER: "admin"
        BASIC_PASS: "admin"
    ports:
      - "80:80"
    networks:
      - front
networks:
  esnet:
    driver: bridge
  front:
    driver: bridge
